defmodule MplBubblegum.KeypairLoader do
  @moduledoc """
  Utility module for loading Solana keypairs from JSON files generated by solana-keygen.
  """

  alias MplBubblegum.Types.Pubkey
  alias MplBubblegum.Native

  def load_keypair(filename) do
    json = Jason.decode!(File.read!(filename))
    case json do
      secret_key when is_list(secret_key) and length(secret_key) == 64 ->
        secret_key_binary = :binary.list_to_bin(secret_key)
        with {:ok, pubkey} <- Native.derive_pubkey_from_secret(secret_key_binary) do
          {:ok, %{
            "public" => Base58.encode(:binary.list_to_bin(pubkey.bytes)),  # Convert list to binary here
            "secret" => secret_key_binary
          }}
        end
      _ ->
        {:error, "Invalid keypair JSON format; expected 64-byte array"}
    end
  end
end